version: '3.8'
services:
  webservice: # 服務名稱
    image: findcarparks-webapp-2023:latest
    ports:
      - "3000:3000"
    environment:
      - .env
    depends_on:
      - mongo
    restart: on-failure

  mongo: # 服務名稱
    image: mongo:latest # dokcer hub
    environment:
      - .env
    volumes:
      - mongo-data:/data/db
      - ./funtion/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"


volumes:
  mongo-data: